#pragma once
#include "../lib/test_work.h"
void learn();
void bio_learn();
void chem_learn();
void physics_learn();
void js_html_learn();
void german_learn();
void lit_learn();
void psychology_learn();
void history_learn();
void geography_learn();
void english_learn();
